highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://crinaoltean.github.io/
author: Crina Oltean

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Crina Oltean's Resume
name: Crina Oltean
email: Email
email_full: mailto:crina_adela_oltean@yahoo.com
website: crinaoltean.github.io
website_full: https://crinaoltean.github.io/
github: github.com/crinaOltean
linkedin: https://linkedin.com/in/crina-adela-oltean/
tel: 0686153501
tel_full: 0686153501
address:
  city: Amsterdam
  country: The Netherlands
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
